### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by natrius** [Zaczero/osm-revert#13]
Hello, 

the UI does not change after pressing "Login with OpenStreetMap". 
![grafik](https://github.com/Zaczero/osm-revert/assets/7243447/20fe9ff7-ed40-4411-bb05-438bc34a7627)

Thats already AFTER i pressed the login button multiple times. I'm logged in, i'm using Mozilla Firefox 116.0.2 (64-Bit) (i tried with edge as well, no change).

For now i used the old one http://revert.osmz.ru/9385 there. 

Best regards

**Comment by Zaczero** [comment]
Resolved, please test. :slightly_smiling_face:

**Comment by natrius** [comment]
Looking good, thanks for that fast response and the awesome tool you created! 

![grafik](https://github.com/Zaczero/osm-revert/assets/7243447/54412d6e-116f-41d0-afc0-f9eb34290043)

**Comment by Zaczero** [comment]
@natrius Just a heads up that a fully autonomous revert is currently in progress due to the complex nature of the situation. If your intention is to revert the "name:ru" entries, I would advise against doing so at this moment. Proper sequencing of the reverts is crucial; attempting to correct them in wrong order might inadvertently introduce offensive content, for which you could be held responsible. Read more details here: https://www.openstreetmap.org/changeset/140164807 and here: https://www.openstreetmap.org/changeset/140162098.
