### ISSUE TITLE
Broken Gravatar avatars.

### ISSUE THREAD

**Issue by mxxcon** [Zaczero/osm-revert#26]
![image](https://github.com/Zaczero/osm-revert/assets/847140/84dbcd71-5ca7-4fdf-9d32-99e87a3f4713)

Chrome Dev console shows the following error message:

> Refused to load the image 'https://www.gravatar.com/avatar/fe48bcc28f68367d65368c90b53a2380.jpg?s=100&d=https%3A%2F%2Fapi.openstreetmap.org%2Fassets%2Favatar_large-54d681ddaf47c4181b05dbfae378dc0201b393bbad3ff0e68143c3d5f3880ace.png' because it violates the following Content Security Policy directive: "img-src 'self' data: https://shields.monicz.dev https://www.openstreetmap.org https://openstreetmap-user-avatars.s3.dualstack.eu-west-1.amazonaws.com".

**Comment by Zaczero** [comment]
This is because osm-revert uses CSP as a modern security measure and OpenStreetMap does not proxy avatar images. Meaning, that all applications need to manually specify all endpoints that OSM may ever use 😵‍💫, and due to lack of documentation I forgot about Gravatar. I'll fix it soon. OpenStreetMap-NG will simplify client CSP policies, making bugs like these less likely to occur (it will proxy and cache the images). 🙂

**Comment by Zaczero** [comment]
Should be fixed now :+1:
