### ISSUE TITLE
How to use filters?

### ISSUE THREAD

**Issue by maro-21** [Zaczero/osm-revert#29]
Another question.
How can I undo a changeset, but without touching, for example, `landuse=grass`?

I tried using filters, but it didn't work. I think it only removed `landuse=grass`, but left the nodes.
I think I typed `node; way[!landuse]` but it didn't remove `landuse`, only some nodes. In any case, it didn't work the way I wanted it to.

**Comment by maro-21** [comment]
Similar question, also related to filters. This is my changeset:
https://www.openstreetmap.org/changeset/147307216
where you can see that I used the filter `node[!natural]; node[!advertising]; way`.
My intention was to leave the trees and ads untouched, but it still removed them:
https://overpass-api.de/achavi/?changeset=147307216
Why?

**Comment by Zaczero** [comment]
The filter lets you specify a union of elements that should be reverted. When specified, elements that match the filter before or after the reverting changeset will be considered.

For example if you want to revert all node fords, you would do:
```
node[ford=yes];
```

If you want to revert all ways that are not highway (and nothing more), you would do:
```
way[!highway];
```

If you want to revert also all nodes and relations, you would do:
```
node;way[!highway];relation;
```

---

To answer your other question, since the filters are a union, you will need to specify restriction on the same element:
```
node[!natural][!advertising];way;
```

So it reverts all nodes that don't have such keys, and all ways.

Btw. you can test your filters without uploading changes by using the "revert and download .osc" button. The .osc file can be manually inspected in some programs and text editors if you are not scared of XML :slightly_smiling_face:.

**Comment by maro-21** [comment]
Thanks.
I added this info to the Wiki article: https://wiki.openstreetmap.org/wiki/Osm-revert
Please take a look if everything is ok.

I wonder how it will be with ways. Suppose a user made a lot of changes in one changeset. Most of it is ok, but he changed the geometry of buildings and only this was not ok. I would like to revert only buildings.
But if I give `way[building];`, it will revert the buildings changed by the user, but won't revert the coordinates of the nodes that were part of those buildings, am I right? If there were some dragged nodes, my revert won't fix this, because it will only revert tags and the list of nodes in [building] ways. So doing a revert with a filter for ways or areas can be unpredictable, no?

**Comment by Zaczero** [comment]
When way is filtered, all of its members are [always included](https://github.com/Zaczero/osm-revert/blob/0a86d18df3ee6ff1b1ae7fb9d3fc9bbea1951760/osm_revert/overpass.py#L130-L131). OSM Revert considers nodes belonging to ways, as being a crucial part of the way. Such nodes are reverted even if you put a different node filter for example:
```
node[bench];way[building];
```

**Comment by maro-21** [comment]
> When ways are filtered, all of their members are [always included](https://github.com/Zaczero/osm-revert/blob/0a86d18df3ee6ff1b1ae7fb9d3fc9bbea1951760/osm_revert/overpass.py#L130-L131)

Thanks, good to know
